######################################################################
# Automatically generated by qmake (3.1) Thu Aug 1 16:09:15 2019
######################################################################

QT = testlib core gui charts
TEMPLATE = app
TARGET = UnitTest
INCLUDEPATH += .
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets printsupport

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
SOURCES = ../src/ProgressDialog.cc ../src/MainWindow.cc ../src/OptionsDialog.cc ../src/ConfirmFile.cc ../src/ErrorTab.cc ../src/SummaryTab.cc ../src/GeneTab.cc ../src/ClonotypeTab.cc ../src/DataTab.cc ../src/ParamsTab.cc ../src/qcustomplot.cc ../src/ErrorXWorker.cc ../src/gui_util.cc ../src/WelcomeTab.cc

HEADERS = ../include/ProgressDialog.hh ../include/MainWindow.hh ../include/OptionsDialog.hh ../include/ConfirmFile.hh ../include/ErrorTab.hh ../include/SummaryTab.hh ../include/GeneTab.hh ../include/ClonotypeTab.hh ../include/DataTab.hh ../include/ParamsTab.hh ../include/qcustomplot.hh ../include/ErrorXWorker.hh ../include/gui_util.hh ../include/WelcomeTab.hh


SOURCES += TestMainWindow.cc

INCLUDEPATH += ../../ErrorX_devel/include/ ../include/
LIBS += -L ../lib/ -lerrorx

OBJECTS_DIR = obj/
MOC_DIR = obj/

CONFIG += c++11
RESOURCES = ../resources.qrc
QMAKE_POST_LINK = bash ../post_build_copy.sh $$TARGET
ICON = ../images/helix_icon.icns

CONFIG += qt debug

ex_extra.files = ../../ErrorX_devel/bin ../../ErrorX_devel/database ../../ErrorX_devel/internal_data ../../ErrorX_devel/lib ../../ErrorX_devel/optional_file ../../ErrorX_devel/model.nnet 
ex_extra.path = Contents/Resources
QMAKE_BUNDLE_DATA += ex_extra

